<?php
/**
 * @author Andrey Mostovoy <stalk.4.me@gmail.com>
 * @var stdClass $PageData данные для страницы
 */
/* @todo Если будут общие правки с MainLandingPage, стоит сделать наследование */
?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LandingPage</title>
<link rel="stylesheet" type="text/css" media="print, projection, screen" href="<?=CSS_PATH?>MainLandingPage/MainLandingPage.css" />
<script type="text/javascript" src="<?=JS_APP_PATH?>MainLandingPage/jquery.knob.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>MainLandingPage/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>MainLandingPage/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>MainLandingPage/jquery.fileupload.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>MainLandingPage/jscolor.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>MainLandingPage/MainLandingPage.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>Sbn/Sbn.js"></script>
<script type="text/javascript" src="<?=JS_APP_PATH?>Sbn/SbnConfigOldNewLanding.js"></script>
