<?php
/**
 * @author Andrey Mostovoy <stalk.4.me@gmail.com>
 * @var stdClass $PageData данные для страницы.
 */
?>
<div class="MainLandingPage">
    <div class="header">
        <div class="sbn top js-sbn-top"><!-- top sbn --></div>
    </div>
    <div class="content">
        <div class="column left">
            <div class="sbn left js-sbn-left"><!-- left sbn --></div>
        </div>
        <div class="column middle">
            <div class="logo"></div>
            <? include 'imageProcessingWidget.phtml' ?>
        </div>
        <div class="column right">
            <div class="sbn right js-sbn-right"><!-- right sbn --></div>
        </div>
    </div>
    <div class="footer">
        <div class="sbn bottom js-sbn-bottom"><!-- bottom sbn --></div>
    </div>
</div>
